#all:	.04_rs-bowtie2-raw-stats .04_rs-bowtie2-tmatic-stats .04_rs-markdup-bowtie2-raw-stats .04_rs-markdup-bowtie2-tmatic-stats
#all:	summary_flagstat.txt
all:	03_markdup-bowtie2-tmatic-stats.txt

02_star-raw-stats.txt:	02_star-raw
	DIR="02_star-raw" ; \
	for file in $$DIR/*.bam; do \
		echo "Processing "$$file ; \
		samtools flagstat $$file >> $$DIR-stats.txt ; \
	done

02_star-tmatic-stats.txt:	02_star-tmatic
	DIR="02_star-tmatic" ; \
	for file in $$DIR/*.bam; do \
		echo "Processing "$$file ; \
		samtools flagstat $$file >> $$DIR-stats.txt ; \
	done

03_markdup-bowtie2-tmatic-stats.txt:	03_markdup-bowtie2-tmatic
	DIR="03_markdup-bowtie2-tmatic" ; \
	for file in $$DIR/*.bam; do \
		echo "Processing "$$file ; \
		samtools flagstat $$file >> $$DIR-stats.txt ; \
	done


02_bowtie2-raw-stats.txt:	02_bowtie2-raw
	DIR="02_bowtie2-raw" ; \
	for file in $$DIR/*.bam; do \
		echo "Processing "$$file ; \
		samtools flagstat $$file >> $$DIR-stats.txt ; \
	done

.04_rs-bowtie2-raw-stats:
	LEN=19 ; \
	DIR="04_rs-bowtie2-raw" ; \
	limits="0.75 0.50 0.25 0.01 0.00" ; \
	for i in $$limits; do \
		for file in `find $$DIR -type f -name "*$$i.bam"`; do \
			samtools flagstat $$file >> $$DIR.$$i-stats.txt ; \
			echo $$file ; \
		done ; \
	done ; \
	touch .04_rs-bowtie2-raw-stats
	
.04_rs-bowtie2-tmatic-stats:
	LEN=19 ; \
	DIR="04_rs-bowtie2-tmatic" ; \
	limits="0.75 0.50 0.25 0.01 0.00" ; \
	for i in $$limits; do \
		for file in `find $$DIR -type f -name "*$$i.bam"`; do \
			samtools flagstat $$file >> $$DIR.$$i-stats.txt ; \
		done ; \
	done ; \
	touch .04_rs-bowtie2-tmatic-stats

.04_rs-markdup-bowtie2-raw-stats:
	LEN=19 ; \
	DIR="04_rs-markdup-bowtie2-raw" ; \
	limits="0.75 0.50 0.25 0.01 0.00" ; \
	for i in $$limits; do \
		for file in `find $$DIR -type f -name "*$$i.bam"`; do \
			samtools flagstat $$file >> $$DIR.$$i-stats.txt ; \
		done ; \
	done ; \
	touch .04_rs-markdup-bowtie2-raw-stats

.04_rs-markdup-bowtie2-tmatic-stats:
	LEN=19 ; \
	DIR="04_rs-markdup-bowtie2-tmatic" ; \
	limits="0.75 0.50 0.25 0.01 0.00" ; \
	for i in $$limits; do \
		for file in `find $$DIR -type f -name "*$$i.bam"`; do \
			samtools flagstat $$file >> $$DIR.$$i-stats.txt ; \
		done ; \
	done ; \
	touch .04_rs-markdup-bowtie2-tmatic-stats

summary_flagstat.txt:
	for file in *-stats.txt ; do \
		echo $$file >> summary_flagstat.txt ; \
		awk ' {printf "%s\t", $$1 } NR % 12 == 0 { printf "\n" } ' < $$file >> summary_flagstat.txt ; \
	done