#!/bin/bash


ADAPTERS="-b AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA -b TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT -b GATCGGAAGAGCACACGTCTGAACTCCAGTCACACAGTGATCTCGTATGCCGTCTTCTGCTTG -b GATCGGAAGAGCACACGTCTGAACTCCAGTCACACTTGAATCTCGTATGCCGTCTTCTGCTTG -b GATCGGAAGAGCACACGTCTGAACTCCAGTCACATCACGATCTCGTATGCCGTCTTCTGCTTG -b GATCGGAAGAGCACACGTCTGAACTCCAGTCACCAGATCATCTCGTATGCCGTCTTCTGCTTG -b GATCGGAAGAGCACACGTCTGAACTCCAGTCACCGATGTATCTCGTATGCCGTCTTCTGCTTG -b GATCGGAAGAGCACACGTCTGAACTCCAGTCACCTTGTAATCTCGTATGCCGTCTTCTGCTTG -b GATCGGAAGAGCACACGTCTGAACTCCAGTCACGATCAGATCTCGTATGCCGTCTTCTGCTTG -b GATCGGAAGAGCACACGTCTGAACTCCAGTCACGCCAATATCTCGTATGCCGTCTTCTGCTTG -b GATCGGAAGAGCACACGTCTGAACTCCAGTCACGGCTACATCTCGTATGCCGTCTTCTGCTTG -b GATCGGAAGAGCACACGTCTGAACTCCAGTCACTAGCTTATCTCGTATGCCGTCTTCTGCTTG -b GATCGGAAGAGCACACGTCTGAACTCCAGTCACTGACCAATCTCGTATGCCGTCTTCTGCTTG -b GATCGGAAGAGCACACGTCTGAACTCCAGTCACTTAGGCATCTCGTATGCCGTCTTCTGCTTG"

ADAPTER="-g GATCGGAAGAGCACACGTCTGAACTCCAGTCACATCACGATCTCGTATGC"

# echo ${1##*/}

# cat $1 | cutadapt -b AAAAAAAAAAAAAAAA -n 1 - | gzip - > $1.dd.gz
# cat $1 | ./btang.sh | ./trimends -n 5 -r 10 -l 30 | cutadapt $ADAPTER -n 1 -m 35 - | gzip > ${1##*/}.gz

# cat $1 | fastx_trimmer -f 5 -Q 33 > gzip.4
# exit
# zcat $1 | ./btang.sh | ./trimends -n 5 -r 10 -l 30 | cutadapt $ADAPTERS -n 1 -M 35 - | gzip > ${1##*/}.gz

#zcat $1 | ./btang.sh | cutadapt $ADAPTERS -n 1 -m 35 - | ./trimends -n 5 -r 10 -l 30 | fastx_trimmer -f 5 -Q 33 -z > ${1##*/}
# cat $1 | cutadapt $ADAPTERS -n 1 -m 35 - | ./trimends -n 5 -r 10 -l 30 | fastx_trimmer -f 5 -Q 33 -z > ${1##*/}

zcat $1 | cutadapt $ADAPTERS - | gzip > $1_cut.gz